/**
 * GENERATED by scripts/gen-feature-guide-auto.mjs — do not edit by hand.
 *
 * Feature keys with a CI-captured screenshot committed under
 * public/feature-guide/auto/. Run `npm run gen:auto-shots` after changing
 * that directory; a test asserts this list matches it.
 */

import type { FeatureKey } from "@event-app/shared";

export const FEATURE_GUIDE_AUTO_KEYS: FeatureKey[] = [
];
