/**
 * GENERATED by scripts/gen-feature-guide-auto.mjs — do not edit by hand.
 *
 * Feature keys with a CI-captured screenshot committed under
 * public/feature-guide/auto/. Run `npm run gen:auto-shots` after changing
 * that directory; a test asserts this list matches it.
 */

import type { FeatureKey } from "@event-app/shared";

export const FEATURE_GUIDE_AUTO_KEYS: FeatureKey[] = [
  "attendee_directory",
  "breakout_style",
  "certificates",
  "cfp",
  "checkin",
  "community",
  "community_general",
  "community_icebreakers",
  "community_local",
  "community_meetups",
  "community_moments",
  "concierge",
  "daily_digest",
  "engagement_points",
  "matchmaker",
  "messaging_dms",
  "messaging_groups",
  "messaging_requests",
  "ops_agent",
  "paid_attendance",
  "readiness",
  "recap_agent",
  "session_feedback",
  "session_likes",
  "session_polls",
  "session_qa",
  "sponsor_outreach",
  "sponsors",
  "timezone_toggle",
  "venue_maps",
  "waitlist_visibility",
];
